### ISSUE TITLE
Will the project be continued?

### ISSUE THREAD

**Issue by ThisisCanada98** [kotasc3/A-New-Dawn-Botania#1]
I enjoy Botania, but with the recent nerfs a fork of it such as yours is just what me and my friends are looking for. I am wondering is the project going to be continued and is it in a playable state at this moment in time?

**Comment by kotasc3** [comment]
It will be continued and it is in a perfectly playable state, but I cannot possibly test everything alone. If some sort of bug arises feel free to let me know

**Comment by ThisisCanada98** [comment]
Okay thank you very much. 0/

**Comment by kotasc3** [comment]
no problem

**Comment by Fortist** [comment]
Welcome back~
