### ISSUE TITLE
Is this still being worked on?

### ISSUE THREAD

**Issue by Nova001Sol** [kotasc3/A-New-Dawn-Botania#10]
I'm asking because the fork is... four versions behind Botania now, and at the time of writing the last commit you made was over two weeks ago. Thank you for reading and I'm sorry for bothering you.

**Comment by kotasc3** [comment]
Yeah, I'll probably have a new release out sometime tonight(EST), Been caught up with exams and what not.

**Comment by Nova001Sol** [comment]
Cool, thanks.
