### ISSUE TITLE
Is this going to update anytime soon?

### ISSUE THREAD

**Issue by raxixor** [kotasc3/A-New-Dawn-Botania#12]
Botania's at 237 already, would like to see a new version.

**Comment by Nova001Sol** [comment]
Well, last time this was asked the dev was busy with exams and what have you. So while I have no doubt the update will come, it might take some time.

**Comment by raxixor** [comment]
I hope it's sooner rather than later.

**Comment by kotasc3** [comment]
Updated on CurseForge, may take a few minutes for the upload to be approved.

**Comment by Nova001Sol** [comment]
Funny how Vazkii updated just after you did, almost like he did it on purpose.
