### ISSUE TITLE
Possible slab ID conflict

### ISSUE THREAD

**Issue by ThisisCanada98** [kotasc3/A-New-Dawn-Botania#2]
When trying to load the game I get this crash. Im just about to see if disabling the slabs gets rid of the problem.

http://pastebin.com/8beUpi55

**Comment by ThisisCanada98** [comment]
Disabling slabs in the config did not do anything.

**Comment by kotasc3** [comment]
fixed in the latest release

**Comment by ThisisCanada98** [comment]
You are amazing! Thanks again.
