### ISSUE TITLE
This fork and Forbidden Magic don't work together

### ISSUE THREAD

**Issue by manoftron** [kotasc3/A-New-Dawn-Botania#4]
Enabling Botania cross interaction for Forbidden Magic causes it to crash. I know mod interaction is probably low on the list, but just pointing this out.

**Comment by kotasc3** [comment]
Logs? From what I can tell it is working fine.

**Comment by manoftron** [comment]
Sorry about this, but you're right, it's something with Forbidden Magic itself.

**Comment by kotasc3** [comment]
No worries.
