### ISSUE TITLE
Unable to compile on Windows

### ISSUE THREAD

**Issue by TomeWyrm** [kotasc3/A-New-Dawn-Botania#5]
I'm betting dollars to donuts I'm screwing something up somewhere, but I can't get the mod to compile successfully.

I have Gradle 2.2.1 installed on my machine, and run "gradle build.gradle" in the directory via CLI.

It spits out this error at me.
"Task 'build.gradle' not found in root project 'A-New-Dawn-Botania'."

I've successfully compiled other mods before, so I have no idea what I'm doing wrong

**Comment by kotasc3** [comment]
Make sure you are in the directory and then run gradle setupDevWorkspace build (or what ever else you may want to run) Also you will need to drop the deobfuscated jar of baubles into a folder called libs in the root directory

**Comment by TomeWyrm** [comment]
There were multiple things I was forgetting. I apparently uninstalled the JDK a while back as well.

The file built successfully!

Thanks for your help kotasc! I so need to actually learn to program from the ground up instead of the way I learned all my current information (jumping in the deep end and only learning enough to finish the task at hand. Also relying heavily on Google :smile:)

Will I need to setupDevWorkspace from this point forwards, or should I simply be able to run a simple build command?

**Comment by kotasc3** [comment]
You only need to run the setupDevWorkspace task once, after that you can run and rerun the build task as much as your please. If you need any other help feel free to ask
