### ISSUE TITLE
Crash in creative

### ISSUE THREAD

**Issue by D4r33lMistaTwista** [kotasc3/A-New-Dawn-Botania#8]
Got this when I attempted to open the creative tab.

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 10/14/15 10:58 AM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at vazkii.botania.common.core.BotaniaCreativeTab.addBlock(BotaniaCreativeTab.java:418)
	at vazkii.botania.common.core.BotaniaCreativeTab.func_78018_a(BotaniaCreativeTab.java:397)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:479)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1640)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at vazkii.botania.common.core.BotaniaCreativeTab.addBlock(BotaniaCreativeTab.java:418)
	at vazkii.botania.common.core.BotaniaCreativeTab.func_78018_a(BotaniaCreativeTab.java:397)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_147050_b(GuiContainerCreative.java:479)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146286_b(GuiContainerCreative.java:456)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:306)
	at net.minecraft.client.gui.inventory.GuiContainer.func_146274_d(GuiContainer.java)
	at net.minecraft.client.gui.inventory.GuiContainerCreative.func_146274_d(GuiContainerCreative.java:566)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:268)

-- Affected screen --
Details:
	Screen name: net.minecraft.client.gui.inventory.GuiContainerCreative

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['PlotwistInc'/249, l='MpServer', x=122.61, y=88.62, z=232.78]]
	Chunk stats: MultiplayerChunkCache: 120, 120
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (124,64,252), Chunk: (at 12,4,12 in 7,15; contains blocks 112,0,240 to 127,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1260 game time, 1260 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 101 total; [EntityZombie['Zombie'/2070, l='MpServer', x=147.50, y=28.00, z=270.50], EntityBat['Bat'/7230, l='MpServer', x=115.69, y=48.00, z=296.94], EntityChicken['Chicken'/64, l='MpServer', x=56.50, y=70.00, z=190.50], EntityChicken['Chicken'/65, l='MpServer', x=57.50, y=70.00, z=192.50], EntityChicken['Chicken'/66, l='MpServer', x=57.50, y=71.00, z=189.50], EntitySpider['Spider'/2114, l='MpServer', x=162.50, y=44.00, z=273.50], EntityChicken['Chicken'/67, l='MpServer', x=56.50, y=71.00, z=189.50], EntityPig['Pig'/69, l='MpServer', x=82.25, y=84.00, z=153.09], EntityPig['Pig'/70, l='MpServer', x=86.03, y=83.00, z=157.88], EntityPig['Pig'/71, l='MpServer', x=78.38, y=84.00, z=158.31], EntityPig['Pig'/72, l='MpServer', x=81.50, y=84.00, z=158.50], EntityChicken['Chicken'/73, l='MpServer', x=80.56, y=74.00, z=289.34], EntityChicken['Chicken'/74, l='MpServer', x=79.34, y=73.00, z=280.53], EntityChicken['Chicken'/75, l='MpServer', x=72.53, y=70.00, z=283.47], EntityChicken['Chicken'/76, l='MpServer', x=74.56, y=73.00, z=280.53], EntitySheep['Sheep'/84, l='MpServer', x=88.50, y=83.00, z=176.50], EntitySheep['Sheep'/85, l='MpServer', x=90.50, y=81.00, z=177.50], EntitySheep['Sheep'/86, l='MpServer', x=90.50, y=80.00, z=181.50], EntitySheep['Sheep'/87, l='MpServer', x=88.50, y=83.00, z=172.50], EntityZombie['Zombie'/2151, l='MpServer', x=113.22, y=72.00, z=266.78], EntityItem['item.tile.arsmagica2:tarmaroot'/108, l='MpServer', x=146.88, y=22.13, z=276.13], EntityPig['Pig'/109, l='MpServer', x=141.47, y=101.00, z=296.53], EntityPig['Pig'/110, l='MpServer', x=143.47, y=98.00, z=296.41], EntityPig['Pig'/111, l='MpServer', x=146.50, y=98.00, z=299.50], EntityPig['Pig'/112, l='MpServer', x=145.50, y=94.00, z=296.50], EntityPig['Pig'/117, l='MpServer', x=156.94, y=76.00, z=263.66], EntityPig['Pig'/118, l='MpServer', x=162.06, y=75.00, z=258.94], EntityPig['Pig'/119, l='MpServer', x=155.53, y=76.00, z=264.03], EntityPig['Pig'/120, l='MpServer', x=153.03, y=76.00, z=261.03], EntityZombie['Zombie'/1144, l='MpServer', x=77.50, y=24.00, z=158.50], EntitySheep['Sheep'/121, l='MpServer', x=164.03, y=72.00, z=250.50], EntitySheep['Sheep'/122, l='MpServer', x=162.47, y=72.00, z=250.50], EntitySheep['Sheep'/123, l='MpServer', x=157.50, y=76.00, z=251.91], EntitySheep['Sheep'/124, l='MpServer', x=162.13, y=72.00, z=248.16], EntityPig['Pig'/125, l='MpServer', x=158.44, y=75.00, z=279.59], EntityPig['Pig'/126, l='MpServer', x=155.50, y=76.00, z=277.50], EntityPig['Pig'/127, l='MpServer', x=161.25, y=75.00, z=278.75], EntityPig['Pig'/128, l='MpServer', x=161.19, y=74.00, z=280.75], EntityZombie['Zombie'/7318, l='MpServer', x=166.50, y=48.00, z=298.50], EntitySkeleton['Skeleton'/7319, l='MpServer', x=165.50, y=49.00, z=305.09], EntityPig['Pig'/153, l='MpServer', x=173.50, y=65.00, z=308.50], EntityPig['Pig'/154, l='MpServer', x=176.50, y=65.00, z=301.31], EntityPig['Pig'/155, l='MpServer', x=178.50, y=67.00, z=311.22], EntityPig['Pig'/156, l='MpServer', x=172.50, y=70.00, z=307.50], EntityPig['Pig'/169, l='MpServer', x=184.03, y=72.00, z=261.19], EntityPig['Pig'/170, l='MpServer', x=185.50, y=73.00, z=255.50], EntityPig['Pig'/171, l='MpServer', x=187.91, y=72.00, z=259.63], EntityPig['Pig'/172, l='MpServer', x=190.50, y=73.00, z=257.72], EntityChicken['Chicken'/173, l='MpServer', x=187.50, y=72.00, z=265.41], EntityChicken['Chicken'/174, l='MpServer', x=193.44, y=72.00, z=265.53], EntityChicken['Chicken'/175, l='MpServer', x=187.56, y=73.00, z=257.59], EntityChicken['Chicken'/176, l='MpServer', x=186.47, y=72.00, z=265.41], EntityItem['item.item.bone'/3263, l='MpServer', x=174.25, y=54.13, z=274.34], EntityCreeper['Creeper'/2241, l='MpServer', x=111.00, y=29.00, z=268.59], EntitySkeleton['Skeleton'/2243, l='MpServer', x=111.50, y=27.00, z=279.50], EntitySkeleton['Skeleton'/2288, l='MpServer', x=57.41, y=26.00, z=288.06], EntitySkeleton['Skeleton'/2289, l='MpServer', x=58.50, y=26.00, z=287.50], EntityEnderman['Enderman'/7409, l='MpServer', x=91.50, y=68.00, z=214.50], EntityCreeper['Creeper'/2290, l='MpServer', x=57.50, y=26.00, z=285.50], EntityZombie['Zombie'/7410, l='MpServer', x=87.50, y=68.00, z=215.50], EntityGaiaBoneKnight['Bone Knight'/1268, l='MpServer', x=60.50, y=27.00, z=202.50], EntityCreeper['Creeper'/6391, l='MpServer', x=136.50, y=39.00, z=311.50], EntityCreeper['Creeper'/6393, l='MpServer', x=139.50, y=38.00, z=308.94], EntityClientPlayerMP['PlotwistInc'/249, l='MpServer', x=122.61, y=88.62, z=232.78], EntityZombie['Armored Zombie'/2329, l='MpServer', x=139.50, y=81.00, z=295.50], EntityItem['item.item.ImmersiveEngineering.seed.hemp'/5401, l='MpServer', x=170.78, y=73.13, z=207.63], EntityZombie['Zombie'/2341, l='MpServer', x=55.50, y=72.00, z=164.50], EntityBat['Bat'/7472, l='MpServer', x=43.75, y=29.00, z=196.10], EntityBat['Bat'/7486, l='MpServer', x=168.00, y=51.00, z=297.72], EntityBat['Bat'/7487, l='MpServer', x=42.93, y=27.00, z=224.71], EntityBat['Bat'/1345, l='MpServer', x=139.84, y=50.00, z=214.13], EntityBat['Bat'/1347, l='MpServer', x=137.56, y=54.00, z=235.69], EntityZombie['Zombie'/2432, l='MpServer', x=148.50, y=33.00, z=298.50], EntityConcussionCreeper['Concussion Creeper'/7563, l='MpServer', x=127.50, y=40.00, z=265.50], EntitySpider['Spider'/1470, l='MpServer', x=124.84, y=72.00, z=306.84], EntityZombie['Zombie'/7626, l='MpServer', x=44.45, y=31.00, z=193.50], EntityZombie['Zombie'/7627, l='MpServer', x=43.50, y=29.00, z=195.50], EntityGaiaNaga['Naga'/2536, l='MpServer', x=65.50, y=72.00, z=290.50], EntityItem['item.item.feather'/4585, l='MpServer', x=186.38, y=72.13, z=263.50], EntityItem['item.tile.gravel'/4587, l='MpServer', x=139.19, y=22.13, z=276.19], EntityCreeper['Creeper'/2590, l='MpServer', x=54.59, y=29.00, z=196.03], EntityBat['Bat'/6694, l='MpServer', x=172.38, y=47.00, z=229.97], EntityBat['Bat'/6701, l='MpServer', x=104.44, y=28.29, z=270.59], EntityBat['Bat'/6714, l='MpServer', x=193.69, y=40.00, z=225.94], EntityBat['Bat'/1668, l='MpServer', x=175.66, y=45.10, z=278.25], EntityBat['Bat'/1673, l='MpServer', x=135.56, y=58.00, z=211.25], EntityBat['Bat'/1688, l='MpServer', x=154.78, y=22.10, z=269.38], EntityZombie['Zombie'/6869, l='MpServer', x=77.50, y=46.00, z=257.50], EntityGaiaCreep['Creep'/6870, l='MpServer', x=78.50, y=46.00, z=255.88], EntitySkeleton['Skeleton'/1803, l='MpServer', x=137.50, y=20.00, z=222.50], EntityConcussionCreeper['Concussion Creeper'/6932, l='MpServer', x=122.50, y=40.00, z=260.50], EntityBat['Bat'/914, l='MpServer', x=123.28, y=39.00, z=262.75], EntityBat['Bat'/915, l='MpServer', x=122.66, y=47.00, z=273.75], EntityBat['Bat'/921, l='MpServer', x=134.13, y=37.00, z=310.78], EntityCreeper['Creeper'/938, l='MpServer', x=60.50, y=44.00, z=255.50], EntityZombie['Zombie'/1966, l='MpServer', x=139.03, y=39.00, z=312.66], EntityZombie['Zombie'/1967, l='MpServer', x=137.50, y=39.00, z=311.50], EntityCreeper['Creeper'/1970, l='MpServer', x=154.50, y=17.00, z=218.50], EntitySkeleton['Skeleton'/1972, l='MpServer', x=153.50, y=17.00, z=219.50], EntityBat['Bat'/961, l='MpServer', x=135.75, y=41.00, z=273.50], EntityZombie['Zombie'/2035, l='MpServer', x=140.59, y=38.00, z=308.28]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:919)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows XP (x86) version 5.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 39000328 bytes (37 MB) / 523501568 bytes (499 MB) up to 523501568 bytes (499 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1448 39 mods loaded, 39 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	Forge{10.13.4.1448} [Minecraft Forge] (forge-1.7.10-10.13.4.1448-1.7.10.jar) 
	UCHIJAAAA	AM2-Preloader{0.0.2} [AMCore] (minecraft.jar) 
	UCHIJAAAA	CodeChickenCore{1.0.6.43} [CodeChicken Core] (minecraft.jar) 
	UCHIJAAAA	NotEnoughItems{1.0.4.107} [Not Enough Items] (NotEnoughItems-1.7.10-1.0.4.107-universal.jar) 
	UCHIJAAAA	ThaumicTinkerer-preloader{0.1} [Thaumic Tinkerer Core] (minecraft.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (AnimationAPI-1.7.10-1.2.4.jar) 
	UCHIJAAAA	arsmagica2{1.4.0.008} [Ars Magica 2] (1.7.10_AM2-1.4.0.008(1).jar) 
	UCHIJAAAA	Baubles{1.0.1.10} [Baubles] (Baubles-1.7.10-1.0.1.10.jar) 
	UCHIJAAAA	Thaumcraft{4.2.3.5} [Thaumcraft] (Thaumcraft-1.7.10-4.2.3.5.jar) 
	UCHIJAAAA	Botania{r1.7-511} [A New Dawn: Botania] (A-New-Dawn-Botania r1.7-511.jar) 
	UCHIJAAAA	Waila{1.5.10} [Waila] (Waila-1.5.10_1.7.10.jar) 
	UCHIJAAAA	Automagy{0.26.3} [Automagy] (Automagy-1.7.10-0.26.3.jar) 
	UCHIJAAAA	AWWayofTime{v1.3.3} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.7.10-1.3.3-13.jar) 
	UCHIJAAAA	ChickenChunks{1.3.4.19} [ChickenChunks] (ChickenChunks-1.7.10-1.3.4.19-universal(1).jar) 
	UCHIJAAAA	chocolateQuest{1.0} [Chocolate Quest] (chocolateQuest-1.7.10-1.1d.jar) 
	UCHIJAAAA	DummyCore{1.13} [DummyCore] (DummyCore1.13.jar) 
	UCHIJAAAA	EnderZoo{1.7.10-1.0.15.32} [Ender Zoo] (EnderZoo-1.7.10-1.0.15.32.jar) 
	UCHIJAAAA	ExtraUtilities{1.2.11} [Extra Utilities] (extrautilities-1.2.11.jar) 
	UCHIJAAAA	ThaumicTinkerer{unspecified} [Thaumic Tinkerer] (ThaumicTinkerer-2.5-1.7.10-164.jar) 
	UCHIJAAAA	ForbiddenMagic{1.7.10-0.57} [Forbidden Magic] (Forbidden Magic-1.7.10-0.57.jar) 
	UCHIJAAAA	GrimoireOfGaia{1.0.0} [Grimoire of Gaia 3] (GrimoireOfGaia3-1.7.10-1.2.7.jar) 
	UCHIJAAAA	guideapi{1.7.10-1.0.1-20} [Guide-API] (Guide-API-1.7.10-1.0.1-20.jar) 
	UCHIJAAAA	ImmersiveEngineering{0.5.4} [Immersive Engineering] (ImmersiveEngineering-0.5.4(1).jar) 
	UCHIJAAAA	inventorytweaks{1.59-dev-152-cf6e263} [Inventory Tweaks] (InventoryTweaks-1.59-dev-152.jar) 
	UCHIJAAAA	MapWriter{2.1.8} [MapWriter] (MapWriter-1.7.10-2.1.10.jar) 
	UCHIJAAAA	clayspawn{1.7.10a} [Pam's Clay Spawn] (Pam's Clay Spawn 1.7.10a.jar) 
	UCHIJAAAA	harvestcraft{1.7.10j} [Pam's HarvestCraft] (Pam's HarvestCraft 1.7.10j.jar) 
	UCHIJAAAA	simplerecipes{1.7.10a} [Pam's Simple Recipes] (Pam's Simple Recipes 1.7.10a.jar) 
	UCHIJAAAA	ProjectE{1.7.10-PE1.9.3} [ProjectE] (ProjectE-1.7.10-PE1.9.3h.jar) 
	UCHIJAAAA	RidiculousWorld{0.1} [Ridiculous World] (Ridiculous World-0.4.jar) 
	UCHIJAAAA	Sanguimancy{1.7.10-1.1.9-33} [Sanguimancy] (Sanguimancy-1.7.10-1.1.9-33.jar) 
	UCHIJAAAA	thaumicbases{1.3.1710.2} [Thaumic Bases] (ThaumicBases-1.3.1710.4.jar) 
	UCHIJAAAA	ThaumicEquivalence{1.7.10-1.0.2} [Thaumic Equivalence] (ThaumicEquivalence-1.7.10-1.0.2.jar) 
	UCHIJAAAA	ThaumicExploration{0.6.0} [Thaumic Exploration] (ThaumicExploration-1.7.10-1.1-53.jar) 
	UCHIJAAAA	ThaumicHorizons{1.1.5} [Thaumic Horizons] (thaumichorizons-1.7.10-1.1.6.jar) 
	UCHIJAAAA	TwilightForest{2.3.7} [The Twilight Forest] (twilightforest-1.7.10-2.3.7.jar) 
	UCHIJAAAA	aobd{2.8.4} [Another One Bites The Dust] (AOBD-2.8.4.jar) 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '3.3.0' Renderer: 'GeForce 8400GS/PCI/SSE2'
	A-New-Dawn-Botania: THIS INSTANCE OF MINECRAFT IS USING A FORK OF BOTANIA NOT SANCTIONED BY VAZKII, REPORT ALL CRASHES AT http://bit.ly/1KXdQeZ
	Launched Version: 1.7.10-Forge10.13.4.1448-1.7.10
	LWJGL: 2.9.1
	OpenGL: GeForce 8400GS/PCI/SSE2 GL version 3.3.0, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)

**Comment by kotasc3** [comment]
fixed in the latest release: r1.7-512
